# TODO 根据实际情况将数据源改成mysql等数据库
spring:
  datasource:
    url: jdbc:h2:file:./erupt;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2           #H2控制台访问路径
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    generate-ddl: true
    database: h2